### ISSUE TITLE
Handle errors when starting Subscriber and Publisher

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-common#10]
On both platforms, we aren't handling errors when the Publisher or Subscriber is started. 
For example, starting up the Ably SDK can throw an error that will crash our SDKs.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/ATS-310) by [Unito](https://www.unito.io/learn-more)

**Comment by QuintinWillison** [comment]
Relates to https://github.com/ably/ably-asset-tracking-common/issues/7.
