### ISSUE TITLE
Command line tool to replay previously saved trips

### ISSUE THREAD

**Issue by AndyNicks** [ably/ably-asset-tracking-common#22]
Create a command line tool that allows the user to retrieve saved trip data from Ably channel history and resubmit it (simulate a trip) to the destination Ably account and trackableID. 

Source credentials and configuration data can be obtained from a configuration file. The tool should perform the following tasks:
1. Retrieve the trip dataset from the Ably channel history using provided source credentials and TrackableID.
2. Send the trip data as is to the specified destination Ably account (by default it should be the source Ably account) with the specified TrackableID (the default is the same as the source TrackableID)
3. (optionally) Publish the trip data with adjusted time stamps to simulate the journey taking place now.
4. (optionally) Publish the trip data continuously in a loop. 
5. (optionally) Specify the start and end time for the part of the trip data that user wants to publish.

Essentially, when this tool is used it should be indistinguishable for Subscriber from normal Ably Asset Tracking Publisher.

To add in the future:
- support for S3 as a source for trip data (https://github.com/ably/ably-asset-tracking-common/issues/23)

## Command line syntax

`ably-trip-replay --configuraiton  <file to the configuration file>` 

## Configuration file format

File format: JSON

```javascript
{
source = <S3, Ably>                             // Select the data source AWS S3 or Ably History
sourceCredentials = "path to file"      //  path to a AWS or Ably credentials file for accessing the source file
sourceTrackableID = <>                       // Trackable ID to relpay
destinationCredentials = "path to file"//  path to a file with Ably destination credentials (optional)
destinationTrackableID = <>                //  destination TrackableID  (optional argument)
adjustTimestamps  = <Y, N>                // amend timestamps of saved data to current time (optional)
loop = <Y, N>                                         // replay the trip data in a loop (optional)
historyStartTime = <>                          //Time stamp of the beginning of the replaying data
historyFinishTime = <>                        //Time stamp of the end of the replaying data
}
```

## Ably credentials file format
```javascript
{
ABLY_API_KEY = <>
}
```

## Acceptance criteria
The application must meet the initial requirements in terms of functionality, accept and process the command line parameters described above. In case of errors, display a user-understandable error message 

## Supporting Materials
Existing CLI tool: https://github.com/ably/ably-asset-tracking-common/tree/main/asset-tracking-debugger

@kavalerov @paddybyers

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ATS-380) by [Unito](https://www.unito.io)

**Comment by kavalerov** [comment]
I am going to remove the AWS from this issue, and create a separate issue to add support for AWS, so that we break this down into more manageable chunks

**Comment by kavalerov** [comment]
Thanks @AndyNicks for putting this together. I have added some adjustments. Can you please provide the acceptance criteria as well?

**Comment by kavalerov** [comment]
When re-reading this, I had the following thought - should we potentially just move all the parameters from command line to the configuration file? This way this tool will be much easier to use repeatedly.

**Comment by kavalerov** [comment]
Based on the conversation we had this morning - potentially we can have 2 command line tools: one for downloading data from Ably History to local file in a standardised JSON format, and another one for actually publishing the data (and we can use existing debugger CLI as a starting point for the second one).
