### ISSUE TITLE
Add update interval to publisher location update messages

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-common#29]
### Change to Publishers

The `LocationUpdate` will have a new member `updateInterval` (units TBC, but should match what we use elsewhere in terms of time intervals / durations).

### Change to Subscribers

This would allow subscribers to more accurately render skipped locations when an update is received, with the effect being that the displayed location is intentionally animated from the previously known locations, through the skipped locations and ultimately to the current location over that time period in anticipation of receiving another update after that time.

So, for example, were the following two messages to be received:

- at 00:10, update message 1:
    - `location`: A
- at 00:20, update message 2:
    - `location`: F
    - `skippedLocations`: B, C, D, E
    - `updateInterval`: 10 seconds

Then the subscriber, at the point of receiving message 2, would animate interpolated between the following keyframe locations:

- 00:20: A
- 00:22: B
- 00:24: C
- 00:26: D
- 00:28: E
- 00:30: F

Anticipating that the next update will arrive at 00:30, where the `updateInterval` might be the same or could be different.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ATS-384) by [Unito](https://www.unito.io)

**Comment by ikbalkaya** [comment]
@QuintinWillison I'm assuming that this change is intended for subscribing example app. As far as I know we are able to move or animate markers on Google maps, however I haven't seen that we can give a custom interpolator to that animation. But there is nothing that stops us from wrapping that functionality inside a custom intrepolator.

**Comment by QuintinWillison** [comment]
We've had a potential customer for Ably Asset Tracking tell us that they are less worried about the 'realtime' nature of the updates to subscribers, and that the smoothness of the rendering is more important to them. Therefore, the theory is that even a network update frequency of something like 30 seconds might be frequent enough - as long as the locations received in those updates are rendered at the subscriber end over the next 30 seconds so that they appear smooth (even though they were all captured 30 seconds ago by the publisher, at the point they are rendered in the subscriber view).

Another term for this could be something like "intentional display latency".

**Comment by AndyNicks** [comment]
This issue was closed due to the implementation of a similar solution "Publish expected interval after which a batch of new locations will be sent (for subscriber-side rendering)" https://github.com/ably/ably-asset-tracking-android/issues/626 and https://github.com/ably/ably-asset-tracking-android/issues/634 which helps to resolve the issue described in this ticket.
