### ISSUE TITLE
Add platform identifier to `LocationHistoryData` objects

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-asset-tracking-common#63]
As described in #62, the publisher SDK emits {{LocationHistoryData}} objects. These objects can subsequently be serialised and stored for later use. Currently, only the Android SDK emits these objects, but in https://github.com/ably/ably-asset-tracking-swift/issues/111 we'll start emitting them from iOS too. We should add some information (need to determine best format for this) that identifies the platform (possibly even library version) that the data was generated by. We should then add it to the JSON schema created in https://github.com/ably/ably-asset-tracking-common/issues/62.

**Comment by lawrence-forooghian** [comment]
@QuintinWillison @KacperKluka @rdeoliv do you have any suggestions about what format this data should take? Are there any examples, either within the asset tracking SDK or more widely at Ably, that we could take advantage of / should be consistent with?

**Comment by QuintinWillison** [comment]
What immediately comes to mind is the similarity to the [Agents](https://github.com/ably/ably-common/tree/main/protocol#agents) supplied by SDKs to the Ably service when they connect.

It doesn't sound like we need to worry about the overhead (in terms of data size) of this additional information, so I would prefer something verbose and unabbreviated. Other than that, no strong opinions. Design away! 😁

**Comment by deanna-lad** [comment]
The corresponding Jira issue is https://ably.atlassian.net/browse/SDK-2717
