### ISSUE TITLE
Decide if the start method of Publisher and Subscriber SDKs should be async

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-common#7]
Currently, the `start()` method is synchronous meaning that it will create and start the Publisher or Subscriber and the code will move on. This may look like the `start()` method is doing only synchronous stuff but in reality, it's calling some async code that can fail. 
Given that, I think that we should change the `start()` to an asynchronous method. This will allow us to inform the SDK user if something bad happens and also let him know exactly when the publisher or subscriber is started and ready to use.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ATS-313) by [Unito](https://www.unito.io/learn-more)

**Comment by QuintinWillison** [comment]
In the Android SDK this issue refers to the `start()` method signatures on both `Builder` interfaces:

- [Publisher.Builder.start()](https://github.com/ably/ably-asset-tracking-android/blob/6681b71daa5844370879aad97778a6c7852b5662/publishing-sdk/src/main/java/com/ably/tracking/publisher/Publisher.kt#L195)
- [Subscriber.Builder.start()](https://github.com/ably/ably-asset-tracking-android/blob/6681b71daa5844370879aad97778a6c7852b5662/subscribing-sdk/src/main/java/com/ably/tracking/subscriber/Subscriber.kt#L104)

In the Cocoa SDK this issue refers to the `start()` method signatures on both builder protocols:

- [PublisherBuilder.start()](https://github.com/ably/ably-asset-tracking-cocoa/blob/92570fbbd107cc43cfd453562a56bfc10f84aa76/Publisher/Sources/PublisherBuilder.swift#L71)
- [SubscriberBuilder.start()](https://github.com/ably/ably-asset-tracking-cocoa/blob/92570fbbd107cc43cfd453562a56bfc10f84aa76/Subscriber/Sources/SubscriberBuilder.swift#L60)
