### ISSUE TITLE
Subscriber should be able to request no resolution after creation

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-common#8]
On iOS it's possible to pass `null` when requesting a resolution for a trackable. On Android, the only situation in which the resolution will be `null` is if it wasn't provided in the subscriber builder. Which platform approach is the correct one?

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ATS-312) by [Unito](https://www.unito.io/learn-more)

**Comment by QuintinWillison** [comment]
It feels like we've discussed this before but have perhaps not formally documented our conclusion, hence the divergence in terms of SDK interface definitions on the subscriber side. If I remember correctly, it never sat comfortably with me the idea of a `sendChangeRequest` method sending a `null` change request, however others were less concerned by this so I'm happy to back down here. 

Thus, my gut feeling tells me we should conform the Android subscribers to support what Cocoa is offering (i.e. allow `null` to be requested), based on the assumption that the publishers at both end *must* be able to handle the scenario that subscribers will often present no resolution preference in their initial presence data.

I also notice as I look at this that the Android subscriber calls this method `sendChangeRequest` but Cocoa is calling it just `changeRequest`. I think the verb prefix is important so this divergence should also be fixed on the Cocoa side.

**Comment by kavalerov** [comment]
So, based on the conversation we just had at refinement, we made a decision that yes, the original requirement was for Subscriber to be able to broadcast that it doesn't have preference regarding resolution. There are still 2 outstanding questions: 

1) Is the current semantic (accepting Optional request) clear enough? 

I personally think it is, but there was discussion in the past wether it is the case - @QuintinWillison please add your thoughts. 

2) IS the naming of the relevant methods correct in general? 

After thinking this through, I actually think that better way to present this in API may be using something like `fun resolutionPreference(Resolution?)`. This way we get away from the "send" verb, and then using Optionals makes perfect sense from semantics point of view. @QuintinWillison @KacperKluka @robertkuraj WDYT?

**Comment by KacperKluka** [comment]
I like the idea of changing the `request` into the `preference` in that method name :+1:

**Comment by QuintinWillison** [comment]
Agreed. Please proceed with @kavalerov's suggestion.
