### ISSUE TITLE
Use Ably and channel state when determining the trackable state in the Subscriber SDK

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-common#9]
On both platforms, we're relying only on the presence messages when determining the trackable state (online, offline, failed). We think that we should also take into consideration the current state of Ably and the channel used for location updates (like we do in the Publisher).

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/ATS-311) by [Unito](https://www.unito.io/learn-more)

**Comment by QuintinWillison** [comment]
I deliberated over classification of this particular issue, but if we're honest with ourselves it sounds like an oversight in terms of implementation that will result in unexpected behaviour at runtime. We should definitely improve this.
